{
 "title": "AutoHealOps Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    { "expr": "app_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Rate Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{\"rate(app_requests_total[1m]) * 60\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{\"rate(app_requests_total[1m]) * 60\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{\"rate(app_requests_total[1m]) * 60\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(app_requests_total[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "app_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "app_errors_total", "legendFormat": "__auto" }
   ]
  }
 ]
}